version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userDB
      - PGDATA=/var/lib/postgresql/data
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - jwt-gql-network

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - jwt-gql-network

volumes:
  db:

networks:
  jwt-gql-network:
    name: jwt-gql-network

